Traceback (most recent call last):
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#import geocat.datafiles as gdf
import numpy as np
from astropy.coordinates.representation import CartesianRepresentation, UnitSphericalRepresentation
from astropy import units

css2c_data = gdf.get('applications_files/ncl_outputs/css2c_output.txt')
css2c_data = np.loadtxt(css2c_data, delimiter=',', skiprows=6)

lat_lon = tuple(map(tuple, (css2c_data[::, 0:2])))
cart_values = css2c_data[::, 2:]
ncl_css2c = dict(zip(lat_lon, cart_values))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 6[0m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mastropy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcoordinates[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrepresentation[39;00m [38;5;28;01mimport[39;00m CartesianRepresentation, UnitSphericalRepresentation
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mastropy[39;00m [38;5;28;01mimport[39;00m units
[0;32m----> 6[0m css2c_data [38;5;241m=[39m [43mgdf[49m[38;5;241m.[39mget([38;5;124m'[39m[38;5;124mapplications_files/ncl_outputs/css2c_output.txt[39m[38;5;124m'[39m)
[1;32m      7[0m css2c_data [38;5;241m=[39m np[38;5;241m.[39mloadtxt(css2c_data, delimiter[38;5;241m=[39m[38;5;124m'[39m[38;5;124m,[39m[38;5;124m'[39m, skiprows[38;5;241m=[39m[38;5;241m6[39m)
[1;32m      9[0m lat_lon [38;5;241m=[39m [38;5;28mtuple[39m([38;5;28mmap[39m([38;5;28mtuple[39m, (css2c_data[::, [38;5;241m0[39m:[38;5;241m2[39m])))

[0;31mNameError[0m: name 'gdf' is not defined

