Traceback (most recent call last):
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.13/asyncio/base_events.py", line 719, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba/envs/geocat-applications/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import math

for key in ncl_relhum.keys():
    assert math.isclose(
        ncl_relhum[key], geocat_relhum[key], rel_tol=1e-05
    )  # within 5 decimal points
------------------


[31m---------------------------------------------------------------------------[39m
[31mKeyError[39m                                  Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[31][39m[32m, line 5[39m
[32m      1[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mmath[39;00m
[32m      3[39m [38;5;28;01mfor[39;00m key [38;5;129;01min[39;00m ncl_relhum.keys():
[32m      4[39m     [38;5;28;01massert[39;00m math.isclose(
[32m----> [39m[32m5[39m         ncl_relhum[key], [43mgeocat_relhum[49m[43m[[49m[43mkey[49m[43m][49m, rel_tol=[32m1e-05[39m
[32m      6[39m     )  [38;5;66;03m# within 5 decimal points[39;00m

[31mKeyError[39m: (np.float64(273.0), np.float64(0.01), np.float64(10000.0))

